[build]
  # Define o diretório base para o build (onde o pnpm install será executado)
  base = "client/"
  # Comando de build a ser executado dentro do diretório base
  command = "pnpm run netlify:build"
  # Diretório de publicação (onde o build final estará)
  publish = "client/dist"

[context.production.environment]
  # Garante que o Netlify use o Node.js 20 (definido no .nvmrc)
  NODE_VERSION = "20"
